import Navbar from "@/components/Navbar"
import "./css/globals.css"
import { Inter } from "next/font/google"
import Providers from "@/components/Providers"
import Head from "next/head"
import { AuthContextProvider } from "@/components/contexts/authContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <Providers>
            <html lang="en">
                <body
                    className={`${inter.className} min-h-screen`}
                    suppressHydrationWarning
                >
                    <Navbar />
                    <div className="container h-100">
                        <AuthContextProvider>{children}</AuthContextProvider>
                    </div>
                </body>
            </html>
        </Providers>
    )
}
